[package]
name = "mtcnn_rs"
version = "0.1.0"
authors = ["Jan Van Sweevelt <vansweej@gmail.com>"]
edition = "2018"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

# run tests in one thread: cargo test -- --test-threads 1
# run tests with stdout: cargo test -- --nocapture

[lib]
crate-type = ["cdylib"]

[dependencies]
#winapi = { version = "0.3.9", features = ["minwindef"] }
#lazy_static = "1.4.0"
#once_cell = "1.4.0"
#log = "0.4.8"
#libc = "0.2.0"
image = "0.23.12"
#approx = "0.3.2"
#ole32-sys = "0.2.0"
ndarray = "0.13.1"
ndarray-image = "0.2"
# pipeline = "0.5.0"
ndarray-npy = "0.6.0"
tensorrt-rs = { git = "https://github.com/vansweej/tensorrt-rs", branch = "develop" }

[dependencies.show-image]
version = "0.6.5"
features = ["image"]